POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "alexandru.olaru@yahoo.com",
    "password": "potterhead"
}

###
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "alexandru.olaru@yahoo.com",
    "password": "potterhead"
}

###
POST http://localhost:3000/auth/signout

### findMe
GET http://localhost:3000/auth/whoami

### findOne
GET http://localhost:3000/auth/2

### find
GET http://localhost:3000/auth?email=alex@yahoo.com

###delete
DELETE http://localhost:3000/auth/1

### update
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "elena.matei@yahoo.com"
}